# Generated by Django 4.2.5 on 2023-11-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustom',
            name='level',
        ),
        migrations.AddField(
            model_name='usercustom',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
