# Generated by Django 4.2.5 on 2023-11-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdriver',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userdriver',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=-6.1661686, max_digits=9),
        ),
        migrations.AlterField(
            model_name='userdriver',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=106.8717686, max_digits=9),
        ),
        migrations.AlterField(
            model_name='userdriver',
            name='photo',
            field=models.ImageField(default='default_user.png', upload_to='user_photos/'),
        ),
    ]
