# Generated by Django 4.2.5 on 2023-11-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_userdriver_email_alter_userdriver_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdriver',
            name='photo',
            field=models.ImageField(default='default_user.png', upload_to='static/user_photos/'),
        ),
    ]
