# Generated by Django 4.2.6 on 2023-11-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_userdriver_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustomer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('customer_name', models.TextField()),
                ('address', models.TextField()),
                ('cp', models.TextField()),
                ('hp', models.TextField()),
                ('photo', models.ImageField(default='default_user.png', upload_to='static/customer_photo/')),
                ('lat', models.DecimalField(decimal_places=6, default=-6.1661686, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, default=106.8717686, max_digits=9)),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
