# Generated by Django 4.2.6 on 2023-11-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_usercustomer_lat_alter_usercustomer_lon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('no_delivery', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('customer_name', models.TextField()),
                ('address', models.TextField()),
                ('cp', models.TextField()),
                ('hp', models.TextField()),
                ('driver_name', models.TextField()),
                ('photo', models.ImageField(default='default_user.png', upload_to='static/delivery_image/')),
            ],
        ),
    ]
