# Generated by Django 4.2.6 on 2023-11-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_delivery_no_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='cust_lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='cust_lon',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='driver_lat',
            field=models.DecimalField(decimal_places=6, default=-6.1661686, max_digits=9),
        ),
        migrations.AddField(
            model_name='delivery',
            name='driver_lon',
            field=models.DecimalField(decimal_places=6, default=106.8717686, max_digits=9),
        ),
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=models.TextField(default='Pickup'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='customer_name',
            field=models.TextField(null=True),
        ),
    ]
